# Generated by Django 2.2.1 on 2019-05-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知识点')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.KnowledgePoint', verbose_name='上级知识点')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('year', models.CharField(max_length=200, verbose_name='试卷年份')),
                ('subject', models.CharField(max_length=200, verbose_name='试卷科目')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.Grade', verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='QuestionDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题目难度')),
            ],
            options={
                'verbose_name': '题目难度',
                'verbose_name_plural': '题目难度',
            },
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题目类型')),
            ],
            options={
                'verbose_name': '题目类型',
                'verbose_name_plural': '题目类型',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='科目名称')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('identity', models.CharField(max_length=200, verbose_name='身份')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=2000, verbose_name='题干')),
                ('answer', models.CharField(max_length=1000, verbose_name='答案')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.QuestionDifficulty', verbose_name='题目难度')),
                ('knowledge_point', models.ManyToManyField(related_name='question', to='TestPaperManager.KnowledgePoint', verbose_name='知识点')),
                ('paper_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.Paper', verbose_name='试卷名称')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.QuestionTypes', verbose_name='题目类型')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.School', verbose_name='学校名称'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPaperManager.Subject', verbose_name='科目名称'),
        ),
    ]
