# Generated by Django 2.0.1 on 2019-05-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestPaperManager', '0002_auto_20190504_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgepoint',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='paper_name',
            new_name='paper',
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TestPaperManager.KnowledgePoint', verbose_name='上级知识点'),
        ),
    ]
