# Generated by Django 2.2.1 on 2019-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPaperManager', '0003_auto_20190521_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(default='1', max_length=1000, verbose_name='选项'),
            preserve_default=False,
        ),
    ]
