# Generated by Django 2.2.1 on 2019-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPaperManager', '0005_questiontypes_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='TestPaperManager/static/TestPaperManager/img')),
            ],
        ),
    ]
