# Generated by Django 2.2.1 on 2019-05-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPaperManager', '0006_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
